#!/usr/bin/env python3
"""
Battle Buddy — GitHub Activity Poller
Runs every 5 minutes via systemd timer on kevcloud.
Polls MkultraUSA/battle_buddy and ships:
  - Metrics via textfile → Alloy textfile collector → Grafana Cloud Prometheus
  - Logs directly to Grafana Cloud Loki
"""
import base64
import json
import os
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone

GITHUB_TOKEN  = os.environ["GITHUB_TOKEN"]
GCLOUD_KEY    = os.environ["GCLOUD_RW_API_KEY"]
REPO          = "MkultraUSA/battle_buddy"
TEXTFILE_PATH = "/var/lib/alloy/textfile/github.prom"

LOKI_URL  = "https://logs-prod-021.grafana.net/loki/api/v1/push"
LOKI_USER = "713695"


def gh(path):
    req = urllib.request.Request(
        f"https://api.github.com/repos/{REPO}{path}",
        headers={
            "Authorization": f"Bearer {GITHUB_TOKEN}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }
    )
    with urllib.request.urlopen(req, timeout=15) as r:
        return json.loads(r.read())


def push_logs(entries: list[tuple]):
    """Push log lines to Loki. entries = [(labels_dict, message)]"""
    now_ns = str(int(time.time() * 1e9))
    streams = []
    for labels, msg in entries:
        labels["host"] = "kevcloud"
        labels["job"]  = "github-poller"
        streams.append({
            "stream": labels,
            "values": [[now_ns, msg]]
        })
    body = json.dumps({"streams": streams}).encode()
    creds = base64.b64encode(f"{LOKI_USER}:{GCLOUD_KEY}".encode()).decode()
    req = urllib.request.Request(
        LOKI_URL,
        data=body,
        headers={
            "Authorization": f"Basic {creds}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    try:
        urllib.request.urlopen(req, timeout=15)
    except Exception as e:
        print(f"[logs] push failed: {e}")


def write_metrics(metrics: list[tuple]):
    """Write Prometheus textfile format for Alloy to scrape."""
    os.makedirs(os.path.dirname(TEXTFILE_PATH), exist_ok=True)
    lines = [f"# Generated by github_poller.py at {datetime.utcnow().isoformat()}"]
    for name, labels, value, help_text in metrics:
        label_str = ",".join(f'{k}="{v}"' for k, v in labels.items())
        lines.append(f"# HELP {name} {help_text}")
        lines.append(f"# TYPE {name} gauge")
        lines.append(f"{name}{{{label_str}}} {value}")
    with open(TEXTFILE_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")


def run():
    metrics    = []
    log_entries = []
    now_iso    = datetime.now(timezone.utc).isoformat()

    # ── Pull Requests ────────────────────────────────────────
    prs      = gh("/pulls?state=all&per_page=50&sort=updated&direction=desc")
    open_prs = [p for p in prs if p["state"] == "open"]
    merged   = [p for p in prs if p.get("merged_at")]

    metrics += [
        ("gh_prs_open",   {"repo": REPO}, len(open_prs),   "Number of open pull requests"),
        ("gh_prs_merged", {"repo": REPO}, len(merged),     "Number of merged pull requests (recent 50)"),
    ]

    for pr in open_prs:
        author = pr["user"]["login"]
        title  = pr["title"]
        number = pr["number"]
        branch = pr["head"]["ref"]
        age_h  = (time.time() - time.mktime(
            time.strptime(pr["created_at"], "%Y-%m-%dT%H:%M:%SZ"))) / 3600

        metrics.append(("gh_pr_age_hours", {
            "repo": REPO, "pr": str(number), "author": author, "branch": branch
        }, round(age_h, 2), "Age of open PR in hours"))

        log_entries.append(({
            "event": "open_pr",
            "author": author,
            "pr": str(number),
            "branch": branch,
        }, f"[PR #{number}] OPEN | {author} | {branch} | age {age_h:.1f}h | {title}"))

    # ── CI / Workflow Runs ───────────────────────────────────
    runs_data     = gh("/actions/runs?per_page=30")
    runs          = runs_data.get("workflow_runs", [])
    pass_count    = sum(1 for r in runs if r.get("conclusion") == "success")
    fail_count    = sum(1 for r in runs if r.get("conclusion") == "failure")
    pending_count = sum(1 for r in runs if r.get("status") in ("in_progress", "queued", "waiting"))

    metrics += [
        ("gh_ci_passing",  {"repo": REPO}, pass_count,    "CI runs with success conclusion"),
        ("gh_ci_failing",  {"repo": REPO}, fail_count,    "CI runs with failure conclusion"),
        ("gh_ci_pending",  {"repo": REPO}, pending_count, "CI runs currently pending or in progress"),
    ]

    for run in runs[:15]:
        conclusion = run.get("conclusion") or "in_progress"
        name       = run.get("name", "?")
        branch     = run.get("head_branch", "?")
        actor      = run.get("actor", {}).get("login", "?")
        level      = "error" if conclusion == "failure" else "info"
        sha        = run.get("head_sha", "")[:8]

        log_entries.append(({
            "event":  "ci_run",
            "status": conclusion,
            "branch": branch,
            "actor":  actor,
            "level":  level,
        }, f"[CI] {conclusion.upper()} | {name} | branch={branch} | actor={actor} | sha={sha}"))

    # ── Recent Commits ───────────────────────────────────────
    commits = gh("/commits?per_page=15")

    for c in commits:
        sha     = c["sha"][:8]
        author  = c["commit"]["author"]["name"]
        message = c["commit"]["message"].split("\n")[0][:120]
        log_entries.append(({
            "event":  "commit",
            "author": author,
            "sha":    sha,
        }, f"[COMMIT {sha}] {author} | {message}"))

    # ── Alert score (open PRs + 3x failing CI) ───────────────
    alert_score = len(open_prs) + (fail_count * 3)
    metrics.append(("gh_alert_score", {"repo": REPO}, alert_score,
                    "Composite alert score: open PRs + 3x failing CI runs"))

    # ── Write & push ─────────────────────────────────────────
    write_metrics(metrics)
    push_logs(log_entries)

    print(f"[{now_iso}] wrote {len(metrics)} metrics to textfile | "
          f"pushed {len(log_entries)} log lines | "
          f"open_prs={len(open_prs)} ci_fail={fail_count} ci_pass={pass_count}")


if __name__ == "__main__":
    run()
