"""A transcription outcome must be classified before it can be alerted on.

`modules/transcription.py` records one of five outcomes per clip, and two Grafana
panels were counting one of them as a fault.

    success  |  empty  |  exception  |  lock_timeout  |  timeout

`empty` means the model returned no text. For a clip of silence or noise that is
**the correct answer** -- PR #162 deliberately stopped paying to transcribe
silence -- and the taxonomy puts `empty` beside `success`, not beside the three
faults. Both panels collapsed it anyway:

  * `Recent Whisper / Transcription Error Logs` matched the literal `empty
    transcript` in Loki, so a quiet afternoon filled a panel called Error Logs
    with expected noise and a busy one left it looking like an outage.
  * `Whisper Error Log Rate` counted `status="empty"` in the numerator, so the
    "error rate" was really "faults plus non-speech".

Both are the same failure the project keeps meeting from the other direction: a
green or blank result that nobody can trust, because the thing being measured was
never the thing being reported.

**The durable part is `OUTCOME_CLASSES`, not the queries.** Adding a status to the
app's taxonomy without classifying it here fails
`test_every_outcome_the_app_can_record_is_classified`, so the next person has to
say whether their new outcome is a fault or an expected result. That is the whole
reason the queries are generated by `scripts/build_error_panels.py` rather than
typed into the UI.
"""

from __future__ import annotations

import importlib.util
import json
import re
import sys
import unittest
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
_FIXTURE = _ROOT / "fixtures" / "grafana" / "bb-transcription-quality.json"
_BUILDER = _ROOT / "scripts" / "build_error_panels.py"
_APP = _ROOT / "modules" / "transcription.py"

_FIXTURE_TITLE = "Recent Whisper / Transcription Error Logs"
_RATE_TITLE = "Whisper Error Log Rate"
_NON_SPEECH_TITLE = "Non-speech clips"


def _load():
    spec = importlib.util.spec_from_file_location("build_error_panels", _BUILDER)
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _panels():
    if not _FIXTURE.exists():
        return []
    doc = json.loads(_FIXTURE.read_text(encoding="utf-8"))

    def walk(panels):
        for panel in (panels or []):
            yield panel
            yield from walk(panel.get("panels"))

    return list(walk(doc.get("panels")))


class TestEveryOutcomeIsClassified(unittest.TestCase):
    """The guard that matters. Adding a status obliges you to classify it."""

    def test_every_outcome_the_app_can_record_is_classified(self):
        mod = _load()
        unclassified = sorted(mod.app_outcome_statuses() - set(mod.OUTCOME_CLASSES))
        self.assertEqual(
            [], unclassified,
            f"modules/transcription.py can record {unclassified} and this script "
            "does not say whether they are faults. Add each to OUTCOME_CLASSES as "
            "'fault' or 'expected' -- otherwise it lands in an error panel or an "
            "error rate by accident, which is how `empty` got there.",
        )

    def test_the_taxonomy_comes_from_the_dict_that_counts_outcomes(self):
        """Not a grep for status-shaped strings.

        That version picked up `started`, which lives in `_metrics_totals` and is
        a lifecycle counter rather than an outcome, so the guard reported a phantom
        unclassified outcome. `status_counts` is the dict that only ever holds
        outcomes, and that is what is read.
        """
        mod = _load()
        statuses = mod.app_outcome_statuses()
        self.assertEqual(
            {"success", "empty", "timeout", "exception", "lock_timeout"}, statuses,
        )
        self.assertNotIn(
            "started", statuses,
            "`started` is a lifecycle counter in _metrics_totals, not an outcome",
        )

    def test_success_and_empty_are_expected_not_faults(self):
        mod = _load()
        self.assertEqual("expected", mod.OUTCOME_CLASSES["success"])
        self.assertEqual("expected", mod.OUTCOME_CLASSES["empty"],
                         "`empty` means the model had no text to return; for "
                         "non-speech audio that is the correct answer")
        self.assertEqual(
            {"exception", "lock_timeout", "timeout"},
            set(mod.FAULT_STATUSES),
            "the fault set is the three genuine failures and nothing else",
        )


class TestNoErrorPanelMatchesAnExpectedOutcome(unittest.TestCase):
    def _error_queries(self):
        for panel in _panels():
            if (panel.get("title") or "") in (_FIXTURE_TITLE, _RATE_TITLE):
                for target in panel.get("targets") or []:
                    if isinstance(target.get("expr"), str):
                        yield panel["title"], target["expr"]

    def test_the_installed_error_panels_are_clean(self):
        mod = _load()
        offenders = []
        for title, expr in self._error_queries():
            for phrase in mod.EXPECTED_LOG_PHRASES:
                if phrase in expr:
                    offenders.append((title, phrase))
            for outcome, kind in mod.OUTCOME_CLASSES.items():
                if kind == "expected" and re.search(
                        rf'status[=~]"?[^}}"]*\b{re.escape(outcome)}\b', expr):
                    offenders.append((title, outcome))
        self.assertEqual(
            [], offenders,
            f"error panels match expected outcomes: {offenders}. An empty "
            "transcript is a recorded outcome, not a fault, and counting it here "
            "means a panel called Error Logs fills with expected noise.",
        )

    def test_the_generated_queries_are_clean(self):
        mod = _load()
        for phrase in mod.EXPECTED_LOG_PHRASES:
            self.assertNotIn(phrase, mod.ERROR_LOG_QUERY)
        for outcome, kind in mod.OUTCOME_CLASSES.items():
            if kind == "expected":
                self.assertNotRegex(
                    mod.ERROR_RATE_QUERY, rf'status=~"[^"]*\b{re.escape(outcome)}\b')

    def test_the_error_rate_names_only_faults(self):
        mod = _load()
        for status in mod.FAULT_STATUSES:
            self.assertIn(status, mod.ERROR_RATE_QUERY)


class TestNonSpeechIsCountedSomewhere(unittest.TestCase):
    """Removing it from the error panels must not make it invisible instead."""

    def test_a_panel_measures_it(self):
        titles = [p.get("title") or "" for p in _panels()]
        self.assertTrue(
            any(t.lower().startswith(_NON_SPEECH_TITLE.lower()) for t in titles),
            f"no non-speech panel on the dashboard; titles were {titles[:12]}",
        )

    def test_it_is_titled_as_a_rate_not_an_error(self):
        for panel in _panels():
            title = (panel.get("title") or "").lower()
            if title.startswith(_NON_SPEECH_TITLE.lower()):
                self.assertNotIn("error", title)
                self.assertNotIn("fail", title)
                return
        self.fail("the non-speech panel is missing")

    def test_there_is_exactly_one_of_it(self):
        """Three installs of the first version left five copies behind."""
        found = [p for p in _panels()
                 if (p.get("title") or "").lower().startswith(_NON_SPEECH_TITLE.lower())]
        self.assertEqual(
            1, len(found),
            f"{len(found)} non-speech panels; the installer nests instead of "
            "siblinging, or removes without adding, and the count diverges",
        )

    def test_no_logs_panel_owns_children(self):
        """The original bug: a stat panel nested inside a logs panel, which
        Grafana accepted silently every time."""
        nested = [p["title"] for p in _panels()
                  if p.get("type") == "logs" and p.get("panels")]
        self.assertEqual([], nested,
                         f"logs panels holding child panels: {nested}. Grafana "
                         "accepts this without complaint and the count grows by "
                         "one per install.",
        )


class TestTheInstallIsIdempotent(unittest.TestCase):
    def test_applying_twice_changes_nothing(self):
        """Proven by running it, not by reading it.

        Two idempotency bugs in this script already: the marker missing from the
        regression row, and the nesting above. The property is cheap to check and
        the third one would have shipped just as quietly.
        """
        mod = _load()
        doc = json.loads(_FIXTURE.read_text(encoding="utf-8"))

        def signature(d):
            return json.dumps(
                [[p.get("title"), p.get("type"), p.get("gridPos"),
                  [(t.get("expr") or "") for t in p.get("targets") or []]]
                 for p in _all(d.get("panels"))],
                sort_keys=True,
            )

        mod._apply(doc)
        after_first = signature(doc)
        second = mod._apply(doc)
        self.assertEqual(after_first, signature(doc),
                         "a second apply changed the dashboard")
        self.assertEqual(0, second, f"a second apply reported {second} changes")

    def test_the_queries_are_unchanged_after_applying(self):
        mod = _load()
        doc = json.loads(_FIXTURE.read_text(encoding="utf-8"))
        mod._apply(doc)
        for panel in _all(doc.get("panels")):
            title = panel.get("title") or ""
            if title == _FIXTURE_TITLE:
                for target in panel["targets"]:
                    self.assertEqual(mod.ERROR_LOG_QUERY, target["expr"])
            elif title == _RATE_TITLE:
                for target in panel["targets"]:
                    self.assertEqual(mod.ERROR_RATE_QUERY, target["expr"])


def _all(panels):
    for panel in (panels or []):
        yield panel
        yield from _all(panel.get("panels"))


if __name__ == "__main__":
    unittest.main()