[program:battlebuddy]
command=/usr/bin/python3 -m flask run --host=0.0.0.0 --port=5000
directory=/opt/data/battle_buddy
environment=PYTHONPATH=/opt/data/battle_buddy
stdout_logfile=/var/log/battlebuddy/stdout.log
stderr_logfile=/var/log/battlebuddy/stderr.log
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=hermes
